cordova
Domino-Blockchain/DWallet pull request #1
Opened 2023-03-03 14:20 UTC by rs-Nenad

Build using cordova
Renaming SOL and Solana -> DOMI and Domichain
Change logo

2023-03-13 13:15 UTC, sviatoslav-alekseev requested changes

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on .eslintcache
> +[{"S:\\DWallet\\src\\index.js":"1","S:\\DWallet\\src\\App.js":"2","S:\\DWallet\\src\\serviceWorker.js":"3","S:\\DWallet\\src\\components\\DialogForm.js":"4","S:\\DWallet\\src\\components\\LoadingIndi
Probably we could delete that cache

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on .eslintcache
> +[{"S:\\DWallet\\src\\index.js":"1","S:\\DWallet\\src\\App.js":"2","S:\\DWallet\\src\\serviceWorker.js":"3","S:\\DWallet\\src\\components\\DialogForm.js":"4","S:\\DWallet\\src\\components\\LoadingIndi
And append to .gitignore

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on package.json
> +  "name": "io.domichain.dwallet",
Something more like app name?
```suggestion
  "name": "domichain-wallet",
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on public/CNAME
> -www.sollet.io
Replace with something like `www.domilet.io`

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/FtxPay/FtxPayDialog.js
> +          Send funds to your domichain wallet from an FTX account, where you can add funds using crypto on multiple blockchains, credit cards, and more.
```suggestion
          Send funds to your Domichain wallet from an FTX account, where you can add funds using crypto on multiple blockchains, credit cards, and more.
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
> +  const [tab, setTab] = useState('spl'); //fixme
We could find same `'spl'` constant and replace that

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
> +      return [ // which to delete / leave
```suggestion
      return [
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
> +  const [tab, setTab] = useState('spl'); //fixme
This should be broken now since we renamed `key="spl"` to `key="dpl"`

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
> +            <Tab label="SPL" key="spl" value="spl" />
```suggestion
            <Tab label="DOMI" key="domi" value="domi" /> 
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
> +        <Tab label="DOMI USDC" key="spl" value="spl" />,
Rename

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
>  function SendSplDialog({ onClose, publicKey, balanceInfo, onSubmitRef }) {
```suggestion
function SendDomiDialog({ onClose, publicKey, balanceInfo, onSubmitRef }) {
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
>      wusdcToSplUsdc || wusdtToSplUsdt || usdcToSplWUsdc
```suggestion
    wusdcToDomiUsdc || wusdtToDomiUsdt || usdcToDomiWUsdc
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/components/SendDialog.js
>              : blockchain === 'sol' && swapCoinInfo.splMint
```suggestion
            : blockchain === 'sol' && swapCoinInfo.domiMint
```

2023-03-13 13:15 UTC, sviatoslav-alekseev commented on src/utils/swap/eth.js
> +        {isExtension == "fixme" ? 'Open sollet.io' : 'Connect to MetaMask'}
Replace `sollet.io`

2023-03-15 13:14 UTC, sviatoslav-alekseev approved these changes

2023-03-15 13:14 UTC, sviatoslav-alekseev commented on src/components/AddTokenDialog.js
> +            {feeFormat.format(tokenAccountCost / LAMPORTS_PER_SOL)} DOMI.
```suggestion
            {feeFormat.format(tokenAccountCost / LAMPORTS_PER_DOMI)} DOMI.
```

2023-03-15 13:14 UTC, sviatoslav-alekseev commented on src/components/DebugButtons.js
>            noSol
```suggestion
          noDomi
```

2023-03-15 13:14 UTC, sviatoslav-alekseev commented on src/components/DomichainIcon.js
> +export default function SolanaIcon() {
```suggestion
export default function DomichainIcon() {
```

2023-03-15 13:21 UTC, rs-Nenad commented on src/components/AddTokenDialog.js
> +            {feeFormat.format(tokenAccountCost / LAMPORTS_PER_SOL)} DOMI.
import { LAMPORTS_PER_SOL } from '@solana/web3.js';

2023-03-15 14:38 UTC, dragvs requested changes

2023-03-15 14:58 UTC, merged