Add transaction history
Domino-Blockchain/DWallet pull request #7
Opened 2023-06-05 13:12 UTC by rs-Nenad

2023-06-07 14:14 UTC, rs-Nenad commented on src/App.js
> +      console.log(moment(1316116057189).fromNow());
removing it right now

2023-06-12 13:34 UTC, dragvs requested changes

2023-06-12 13:34 UTC, dragvs commented on src/App.js
> +    console.log(moment(1316116057189).fromNow());
@rs-Nenad will you update this part as well?

2023-06-13 14:24 UTC, sviatoslav-alekseev commented on src/components/TransactionHistory.js
> +  let transactions = await connection.getConfirmedSignaturesForAddress2(pubkey, {limit: limit});
```suggestion
  let transactions = await connection.getConfirmedSignaturesForAddress2(pubkey, {limit});
```

2023-06-13 14:24 UTC, sviatoslav-alekseev commented on src/components/TransactionHistory.js
> +    const tx = await connection.getParsedConfirmedTransaction(transactions[i].signature)
We could avoid awaits in the loop and do one await via `Promise.all()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2023-06-14 13:20 UTC, dragvs commented on src/components/TransactionHistory.js
> +    const tx = await connection.getParsedConfirmedTransaction(transactions[i].signature)
I'd skip it here

2023-06-14 13:23 UTC, dragvs requested changes

2023-06-14 13:23 UTC, dragvs commented on src/App.js
> +    console.log(moment(1316116057189).fromNow());
```suggestion
    moment.locale(newLang === "zh"? "zh-cn" : newLang)
```

2023-06-14 13:24 UTC, dragvs approved these changes

2023-06-14 14:03 UTC, merged